# Generated by Django 3.1.7 on 2021-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
