# Generated by Django 3.1.7 on 2021-03-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsize_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='size',
        ),
    ]
